//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_BOOKING_SYSTEM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServicesEntities1 : DbContext
    {
        public ServicesEntities1()
            : base("name=ServicesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Facial> Table_Facial { get; set; }
        public virtual DbSet<Table_Facial_Men> Table_Facial_Men { get; set; }
        public virtual DbSet<Table_Gender> Table_Gender { get; set; }
        public virtual DbSet<Table_Haircut_Female> Table_Haircut_Female { get; set; }
        public virtual DbSet<Table_Haircut_Men> Table_Haircut_Men { get; set; }
        public virtual DbSet<Table_Manicure_Female> Table_Manicure_Female { get; set; }
        public virtual DbSet<Table_Manicure_Male> Table_Manicure_Male { get; set; }
        public virtual DbSet<Table_Massage> Table_Massage { get; set; }
        public virtual DbSet<Table_Pedi_Men> Table_Pedi_Men { get; set; }
        public virtual DbSet<Table_Pedicure> Table_Pedicure { get; set; }
        public virtual DbSet<Table_Threading> Table_Threading { get; set; }
        public virtual DbSet<Table_Type_Of_Service> Table_Type_Of_Service { get; set; }
        public virtual DbSet<Table_Venue> Table_Venue { get; set; }
        public virtual DbSet<Table_Wax> Table_Wax { get; set; }
        public virtual DbSet<Table_Threading_Male> Table_Threading_Male { get; set; }
        public virtual DbSet<Table_Wax_Male> Table_Wax_Male { get; set; }
    }
}
