//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_BOOKING_SYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Manicure_Female
    {
        public int ID { get; set; }
        public string TYPES { get; set; }
        public int COST { get; set; }
        public string ITEM { get; set; }
    }
}
