//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_BOOKING_SYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Slot
    {
        public int ID { get; set; }
        public string LOCATION { get; set; }
        public string SLOT { get; set; }
        public string DAY { get; set; }
    }
}
